# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#1-intro'
    weight: 10
  - name: About
    url: '#2-about'
    weight: 20
  - name: Experience
    url: '#3-experience'
    weight: 30
  - name: Services
    url: '#4-services'
    weight: 40
  - name: Projects
    url: '#5-projects'
    weight: 50
  - name: Courses
    url: '#6-courses'
    weight: 60
  - name: People
    url: '#7-people'
    weight: 70
  - name: Publications
    url: '#8-publications'
    weight: 80
  - name: Contact
    url: '#contact'
    weight: 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
